export { default as ChangePassword } from './change-password'
export { default as ResetPassword } from './reset-password'
export { default as DeleteAccount } from './delete-account'
export { default as AdminDeleteAccount } from './delete-account-admin'
export { default as UnlinkDiscord } from './unlink-discord'
export { default as Feedback } from './feedback'
export { default as Welcome } from './welcome'
